steps:

- name: 'gcr.io/cloud-builders/git'
  id: download
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    set -x && \
    git clone https://github.com/datacommonsorg/website.git website-repo && \
    cd website-repo && \
    git checkout $(head -1 ../website/production/commit_hash.txt)

- id: package
  name: 'node'
  entrypoint: /bin/bash
  args:
  - -c
  - |
    cd website-repo/static && \
    npm install && \
    npm run-script build


- id: deploy
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  args:
  - -c
  - |
    cd website-repo/server && \
    gcloud app deploy app_prod.yaml -q \
      --project=datcom-browser-prod \
      --version=$(head -1 ../../website/production/commit_hash.txt)
